### ISSUE TITLE
云端后没有按照时间进行自动检测

### ISSUE THREAD

**Issue by jinfeng1985** [easychen/checkchan-dist#14]
本地浏览器插件可以按照规定时间进行检测，但一同步到云端，就不会自动按照规定时间进行检测了，手动点击检测，云端会检测。
部署：群辉docker
版本：Build.2022.06.09.14.30

**Comment by easychen** [comment]
可能的原因：

① 服务器端没有设置TZ变量，可以通过查看环境变量确认
② 服务器内存不够，运行任务时失败，可以通过docker 容器日志确认

**Comment by jinfeng1985** [comment]
> 可能的原因：
> 
> ① 服务器端没有设置TZ变量，可以通过查看环境变量确认 ② 服务器内存不够，运行任务时失败，可以通过docker 容器日志确认

默认TZ为chognqing  我改成shanghai 也不行，docker内存够的，手动是可以执行的。logs一直是这么几条


wakeup dt=10
wakeup dt=50
file root:
line /usr/local/bin/node /checkchan/api/cron.js > /checkchan/data/app_data/cron.txt
job: 0 /usr/local/bin/node /checkchan/api/cron.js > /checkchan/data/app_data/cron.txt
child running /bin/ash
USER root pid 304 cmd /usr/local/bin/node /checkchan/api/cron.js > /checkchan/data/app_data/cron.txt

**Comment by jinfeng1985** [comment]
如果手动 日志如下：
wakeup dt=10
10:57:27 3|app        | in auto
10:57:27 3|app        | in dom delay =  0
10:57:27 3|app        | in low dom
10:57:28 3|app        | low result undefined
10:57:28 3|app        | 0
10:57:36 3|app        | ret { text: '2 days ago' }
10:57:36 3|app        | save html
10:57:36 3|app        | true 2 days ago dom
crond[9]: wakeup dt=50
crond[9]: file root:

**Comment by easychen** [comment]
首先明确下，同步到云端以后，本地任务是会停止执行的。
---
如果以上没有问题，那么可以检查

1. ./data/app_data/data.json 中的任务是否包含 is_cloud_task:1 字段
2. 查一下  /data/app_data/log.txt 中是否监测到任务

**Comment by jinfeng1985** [comment]
is_cloud_task:1 字段准确，但 /data/app_data/里面只有data.json   没有log.txt文件，我看日志都是在docker容器里的日志里面看的
我只有data.json和image文件夹，没有log.txt.

![Dingtalk_20220610132312](https://user-images.githubusercontent.com/22148953/172996217-ee70dfec-b0d9-43c6-9b3d-1df751734ce1.jpg)
![Dingtalk_20220610132342](https://user-images.githubusercontent.com/22148953/172996223-ebb6946b-71d8-42e7-b6f8-f723ba1a577f.jpg)
![Dingtalk_20220610132503](https://user-images.githubusercontent.com/22148953/172996228-569774d7-9b76-4200-9d14-76afb491023c.jpg)
![Dingtalk_20220610132328](https://user-images.githubusercontent.com/22148953/172996230-0d7d030d-737a-4996-b826-11d33ed1c5a0.jpg)

**Comment by jinfeng1985** [comment]
以上黏贴的日志都是docker中的日志，非本地日志。

**Comment by easychen** [comment]
那你可以在容器里边 /checkchan/data/app_data 目录下运行  node cron.js 看看输出

**Comment by jinfeng1985** [comment]
哈哈 这步骤不会

**Comment by jinfeng1985** [comment]
请问一下    本地路径的装载  是装载  /checkchan/data  还是 /data    我如果装载/data 只有data.json和image文件夹，如果装载/checkchan/data  还有个  user_data,而始终没有 app_data

**Comment by easychen** [comment]
二合一以后的镜像是外部的data 目录挂载到容器内的 /checkchan/data ，为了兼容之前的镜像，支持挂载到 /data 。可以删掉本地的 data 目录， 挂载到容器内的 /checkchan/data 试试。

**Comment by itgoyo** [comment]
@easychen 部署腾讯云也出现类似的问题
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/23348551/174023324-1d21350a-5c7d-4ca6-801c-753f38cf0eec.png">
<img width="857" alt="image" src="https://user-images.githubusercontent.com/23348551/174023354-6c2ca6b7-4036-445d-8650-ba1bf6712217.png">

docker log日志的数据是看的出来是每个时间段都会监测的，但是novnc连接的页面的最后变更时间，没有刷新

安装方式如下：（貌似之前是好的？就早上down  pull 之后发现的，最早的时候是看大大B站时候搭建的）

```
version: '3'
services:
  chrome:
    image: easychen/checkchan:latest
    volumes:
      - "./data:/checkchan/data"
    environment:
      - “CKC_PASSWD=mm"
      - "VDEBUG=OFF"
      - "VNC=ON"
      #- "WIN_WIDTH=414"
      #- "WIN_HEIGHT=896"
      #- "XVFB_WHD=500x896x16"
      - “API_KEY=mm"
      - “ERROR_IMAGE=FULL" # NONE,NORMAL,FULL
      #- "SNAP_URL_BASE=http://ip:4088"
      #- "SNAP_FULL=1"
      - "TZ=Asia/Chongqing"
    ports:
      - "4900:5900" 
      - "4080:8080" 
      - "4088:80”

```
