### ISSUE TITLE
云端监控 

### ISSUE THREAD

**Issue by Ran-Xing** [easychen/checkchan-dist#4]
如果配置了云端监控，则由云端接管监控任务，
有点吃内存，air不太行
还有一个  /home/chrome/app_data /home/chrome/user_data /data 这么多配置我该用哪个？

再就是docker问题
```bash
#!/bin/sh

if [ "$CKC_PASSWD" = "" ]; then
    crond -l 0
    node /api/app.js
else
    XVFB_WHD=${XVFB_WHD:-1220x1020x16}
    echo "Starting Xvfb"
    Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
    sleep 2
    export DISPLAY=:99
    crond -l 0
    pm2 start /x11vnc.sh
    pm2 start /novnc.sh
    pm2 start /api/app.js
    pm2 start src/extension.js --no-daemon

fi
```
这不就搞定了，用户都没有设置 密码，启动个锤子的vnc,对吧，还有你那个docker 有点简陋啊

Dockerfile
```dockerfile
WORKDIR /usr/src/app/
USER root
```

这就搞定了  权限问题，但是可能外面的用户用不了，所以需要外面创建一个 uid 为1000的用户，或者直接用root

还有 你的 /usr/src/app/ /api /data，这文件太乱了吧，兄台，看的我都懵逼了，/usr/src/app/ 这里面也有api，也有data，晕

你能不能给 docker 设置一个tag，latest 默认最新版，但是文档别写最新版，可以浏览器告诉用户该更新了

我后台 watchtower 直接把镜像拉倒最新了，我说怎么收不到通知了，直接蹦了

能不能给普通用户留条路，docker 加个 dingding 不为过吧。。。你收费咋也理解，但是钉钉飞书本来就是免费的，webhook 也是免费的这是关键啊
你app.js 也没做 进程守护，出问题了也不知道弹个通知 告诉用户 你的docker 镜像出问题了

**Comment by Ran-Xing** [comment]
友情赞助你个 github action yaml

```yaml
name: Docker Build

on:
  workflow_dispatch:
  watch:
    types: started

jobs:
  Docker_Build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Docker Login in Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY_ALIYUN }}
          username: ${{ secrets.DOCKERHUB_ACCOUNT_ALIYUN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_ALIYUN }}
      - 
        name: Docker Login in Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Docker Login in Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          file: Dockerfiles/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:v14
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:v14
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            ${{ secrets.DOCKERHUB_REGISTRY_ALIYUN }}/${{ secrets.DOCKERHUB_USERNAME_ALIYUN }}/${{ secrets.DOCKERHUB_REPO }}:v14
            ${{ secrets.DOCKERHUB_REGISTRY_ALIYUN }}/${{ secrets.DOCKERHUB_USERNAME_ALIYUN }}/${{ secrets.DOCKERHUB_REPO }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:v14.cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:v14.cache,mode=max
      - 
        # 更新 hub.docker.com 描述页面
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ SECRETS.DOCKERHUB_USERNAME }}
          password: ${{ SECRETS.DOCKERHUB_PASSWORD }}
          repository: ${{ SECRETS.DOCKERHUB_USERNAME }}/${{ SECRETS.DOCKERHUB_REPO }}
      -
        name: Get Data 
        id: getDingData
        run: |
          set -ex
          # 输出仓库名
          REPOSITORY="${{GITHUB.REPOSITORY}}"
          echo "::set-output name=REPOSITORY::${REPOSITORY#*/}"
          
          # 获取用户仓库信息
          # RESPONSE="$(curl -sLm 10 https://api.github.com/repos/${{ GITHUB.REPOSITORY }})"
          # 建议填写自己的 TOKEN
          RESPONSE="$(curl -sLm 10 https://api.github.com/repos/${{ GITHUB.REPOSITORY }} -H "Authorization: token ${{ SECRETS.TOKEN_GITHUB }}")"
          
          # 获取 用户仓库 设置的 描述，如果为空，可能是没有使用 TOKEN
          DESCRIPTION="$(jq -r .description <(echo ${RESPONSE}))"
          echo "::set-output name=DESCRIPTION::${DESCRIPTION}"

          # 获取 用户仓库 设置的 URL, 如果没有就输出 Github 地址
          URL="$(jq -r .homepage <(echo ${RESPONSE}))"
          if [[ "${URL}" == "null" || "${URL}" == "" ]]; then
            echo "::set-output name=URL::${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}"
          else
            echo "::set-output name=URL::${URL}"
          fi
      - 
        name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ SECRETS.DING_TOKEN }}
          secret: ${{ SECRETS.DING_SECRET }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "${{ steps.getDingData.outputs.DESCRIPTION }}",
                  "title":  "${{ steps.getDingData.outputs.REPOSITORY }} WorkFlow ${{ GITHUB.JOB }} Success!",
                  "picUrl": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                  "messageUrl": "${{ steps.getDingData.outputs.URL }}"
              }
            }
```
